### ISSUE TITLE
Fix NodeMailer

### ISSUE THREAD

**Issue by ski-i** [rohanvarshney/LostThenFound#91]
emails.js doesn't work because NodeMailer fails to log in correctly

**Comment by dbehailu** [comment]
resolved with: https://accounts.google.com/b/0/displayunlockcaptcha . Which unlocks the captcha nodemailer sometimes runs into and has no way to solve automatically.

Future work would include using their recommend OAUTH solution or using a less restrictive email service rather than gmail. More info about solutions here: https://nodemailer.com/usage/using-gmail/
